<section id="<?php echo $anchor3 ?>">
	<?php echo'<h2><span>' . $number3 . '</span> ' . $title3 . '</h2>' // Story Components and Types;?>
	<p>A story page is a type of article, like news articles that you would find on <a href="slice.mit.edu">slice.mit.edu</a>.  This section introduces the site's different story types and the context in which they are used. It outlines the components used to create a story, and illustrates the best practices for authors to follow. Story pages are created by site authors, or content is collected from other MIT sources.</p>
	<div id="<?php echo $anchor3a ?>">
		<?php echo'<h3>' . $title3a . '</h3>'; // Story Components ?>
		<p> A story is comprised of several different components, ranging from a story's photograpy and text, to is metadata and other related content pieces.  Please see the content below for information about each story component.</p>
		<a href="images/stories/storycomponents.png" data-lightbox="<?php echo $title3a ?>-1" class="img-link"><img src="images/stories/storycomponents.png" alt="<?php echo $title3a ?> Screen Shot"></a>
		<div class="split">
			<ul>
				<li>
					<h4><span class="letter">A</span>Main Story Photo</h4>
					<p>This is the main visual representation of a story and will be featured in any context where a story's primary photo is needed, such as in an article list. Information on how to select a photo can be found in the <?php echo $photo_guide_link //photography guide link ?>.</p>
				</li>
				<li>
					<h4><span class="letter">B</span>Story Headline</h4>
					<p>This is the primary heading of a story and will be featured in any context where a story's heading is needed, such as on a category page. Headline placements and character counts can be found in the <a href="<?php echo $copy_guide_link?>182007013" target="_blank">copy specs visual guide</a>.</p>
				</li>
				<li>
					<h4><span class="letter">C</span>Story Metadata</h4>
					<p>Metadata is a short set of information that describes a story's attributes.  Meta information includes a story's <em>author</em>, the source <em>url</em> of the story, its <em>media type</em>, and the <em>date</em> it was published.</p>
				</li>
				<li>
					<h4><span class="letter">D</span>Topic/Category Tags</h4>
					<p>Topic tags display the topic(s) or categorie(s) that a story is associated with and help define the context of where a story is located.  Clicking on a topic tag will generate a landing page with stories related to that topic.</p>
				</li>
				<li>
					<h4><span class="letter">E</span>Story Body Content</h4>
					<p>This is the main body content of a story, featuring paragraphs and different inset content types.  Character counts for story body content can be found in the <a href="<?php echo $copy_guide_link?>182009564" target="_blank">copy specs visual guide</a>.</p>
				</li>
				<li>
					<h4><span class="letter optional">F</span>Media Carousel</h4>
					<p>Media carousels allow authors to include several pieces of media into a story page. Carousels have the ability to hold photos, videos and sound files. A media carousel can be utilized as a visual interruptor when authoring a story.</p>
				</li>
				<li class="break">
					<h4><span class="letter optional">G</span>Inset Quote</h4>
					<p>An inset quote is a featured text fragment used to emphasise a particular sentence or message within a story. Inset quotes can be utilized as visual interruptors when authoring a story. Character counts for inset quotes can be found in the <a href="<?php echo $copy_guide_link?>182007013" target="_blank">copy specs visual guide.</a></p>
				</li>
				<li>
					<h4><span class="letter optional">H</span>Factoid</h4>
					<p>A factoid is a highlighted portion of content that emphasizes a particular fact in a story. Factoids can be utilized as visual interruptors when authoring a story.</p>
				</li>
				<li>
					<h4><span class="letter optional">I</span>Inset Image</h4>
					<p>An inset image can be utilized as a visual interruptor when authoring a story, and are sometimes associated with a quote or factoid. Information on how to select photos can be found in the <?php echo $photo_guide_link //photography guide link ?>. Character counts for inset image captions can be found in the <a href="<?php echo $copy_guide_link?>182009564" target="_blank">copy specs visual guide.</a>
					</p>
				</li>
				<li>
					<h4><span class="letter">J</span>Next Up Stories</h4>
					<p>Next Up stories are automatically generated by the system.  They feature the main photo, headline, and metadata for each story.</p>
				</li>
				<li>
					<h4><span class="letter">K</span>Media Flag</h4>
					<p>Media flags denote the type of media content that is associated with a story. Each flag is automatically generated based on the media type.</p>
				</li>
				<li>
					<h4><span class="letter">L</span>Related / Recommended Stories</h4>
					<p>Related stories are generated by the system via categories and tags, or they can be directly currated by authors.</p>
				</li>
				
			</ul>
		</div>
	</div>
	<div id="<?php echo $anchor3b ?>">
		<?php echo'<h3>' . $title3b . '</h3>'; // Feature Story ?>
		<p>Featured stories are the most robust of all story template types.  Featured stories are meant to be rich reading experiences and should include multiple inset elements, such as carousels, embedded media, factoids and quotes. Feature story templates should be used for important articles and to highlight the profiles of influential people.  Some best practices for featured stories are listed below.</p>
		<div class="split shaded">
			<h6><?php echo $title3b;?> Best Practices</h6>
			<div class="left do">
				<h5>Do</h5>
				<a href="images/stories/feat_do_full.png" data-lightbox="<?php echo $title3b ?>dos-1" class="img-link"><img src="images/stories/feat_do_thumb.png" alt="<?php echo $title3b ?> Do's Screen Shot" class=""></a>
				<ul>
					<li><p>Include multiple page interruptors, such as block quotes and inset photography, to divide up the content keep the story visually interesting.</p></li>
					<li><p>Keep the story length to around 1600 words, excluding media and photography captions.  Character counts for feature story elements can be found in the <a href="<?php echo $copy_guide_link?>182009564" target="_blank">copy specs visual guide.</a></p></li>
				</ul>
			</div>
			<div class="right dont break">
				<h5>Don't</h5>
				<a href="images/stories/feat_dont_full.png" data-lightbox="<?php echo $title3b ?>donts-1" class="img-link"><img src="images/stories/feat_dont_thumb.png" alt="<?php echo $title3b ?> Dont's Screen Shot" class=""></a>
				<ul>
					<li><p>Avoid using too many page interruptors, as it will make story difficult to follow.</p></l>
					<li><p>Do not use multiple instances of the same type of interruptor in succession.</p></li>
					<li><p>Don't place page interruptors too closely together to avoid making the page feel crowded.</p></li>
				</ul>
			</div>
		</div>
	</div>
	<div id="<?php echo $anchor3c ?>">
		<?php echo'<h3>' . $title3c . '</h3>'; // Visual Story ?>
		<p>Visual stories are used as a general purpose article template, and should be utilized for the majority of the articles published on the site.  Visual stories have many of the same attributes as featured stories, but do not contain as much content.  Visual stories use a minimum number of inset story components in order to keep the content succinct.</p>
		<div class="split">
			<div class="left">
				<a href="images/stories/visual_components_a.png" data-lightbox="<?php echo $title3c ?>-1" class="img-link"><img src="images/stories/visual_components_a.png" alt="<?php echo $title3c ?> Screen Shot" class="two-thirds"></a>
			</div>
			<div class="right">
				<a href="images/stories/visual_components_b.png" data-lightbox="<?php echo $title3c ?>-1-1" class="img-link"><img src="images/stories/visual_components_b.png" alt="<?php echo $title3c ?> Screen Shot" class="two-thirds"></a>
			</div>
		</div>
		<div class="split">
			<ul>
				<li>
					<h4><span class="letter">A</span>Main Story Photo</h4>
					<p>This is the main visual representation of a story and will be featured in any context where a story's primary photo is needed, such as in an article list. Information on how to select a photo can be found in the <?php echo $photo_guide_link //photography guide link ?>.</p>
				</li>
				<li>
					<h4><span class="letter">B</span>Story Headline</h4>
					<p>This is the primary heading of a story and will be featured in any context where a story's heading is needed, such as on a category page. Headline placements and character counts can be found in the <a href="<?php echo $copy_guide_link?>182007013" target="_blank">copy specs visual guide</a>.</p>
				</li>
				<li>
					<h4><span class="letter">C</span>Story Metadata</h4>
					<p>Metadata is a short set of information that describes a story's attributes.  Meta information includes a story's <em>author</em>, the source <em>url</em> of the story, its <em>media type</em>, and the <em>date</em> it was published.</p>
				</li>
				<li>
					<h4><span class="letter">D</span>Topic/Category Tags</h4>
					<p>Topic tags display the topic(s) or categorie(s) that a story is associated with and help define the context of where a story is located.  Clicking on a topic tag will generate a landing page with stories related to that topic.</p>
				</li>
				<li class="break">
					<h4><span class="letter">E</span>Story Body Content</h4>
					<p>This is the main body content of a story, featuring paragraphs and different inset content types.  Character counts for story body content can be found in the <a href="<?php echo $copy_guide_link?>182009564" target="_blank">copy specs visual guide</a>.</p>
				</li>
				<li>
					<h4><span class="letter optional">F</span>Inset Quote</h4>
					<p>An inset quote is a featured text fragment used to emphasise a particular sentence or message within a story. Inset quotes can be utilized as visual interruptors when authoring a story. Character counts for inset quotes can be found in the <a href="<?php echo $copy_guide_link?>182007013" target="_blank">copy specs visual guide.</a></p>
				</li>
				<li>
					<h4><span class="letter">G</span>Next Up Stories</h4>
					<p>Next Up stories are automatically generated by the system.  They feature the main photo, headline, and metadata for each story.</p>
				</li>
				<li>
					<h4><span class="letter">H</span>Related / Recommended Stories</h4>
					<p>Related stories are generated by the system via categories and tags, or they can be directly currated by authors.</p>
				</li>
				
			</ul>
		</div>
		<div class="split shaded" id="visualstorydosdonts">
			<h6><?php echo $title3c;?> Best Practices</h6>
			<div class="left do">
				<h5>Do</h5>
				<a href="images/stories/visualstorydo.png" data-lightbox="<?php echo $title3c ?>dos-1" class="img-link"><img src="images/stories/visualstorydothumb.png" alt="<?php echo $title3c ?> Do's Screen Shot" class=""></a>
				<ul>
					<li><p>Use a maximum of 2 page interruptors so that the story remains short.</p></li>
					<li><p>Keep the story length to around 1600 words, excluding media and photography captions.  Character counts for feature story elements can be found in the <a href="<?php echo $copy_guide_link?>182009564" target="_blank">copy specs visual guide.</a></p></li>
				</ul>
			</div>
			<div class="right dont break">
				<h5>Don't</h5>
				<a href="images/stories/visualstorydontsthumb.png" data-lightbox="<?php echo $title3c ?>dos-1" class="img-link"><img src="images/stories/visualstorydontsthumb.png" alt="<?php echo $title3c ?> Do's Screen Shot" class=""></a>
				<ul>
					<li><p>Avoid using too many page interruptors, as it will make story difficult to follow.</p></l>
					<li><p>Do not use multiple instances of the same type of interruptor in succession.</p></li>
					<li><p>Don't place page interruptors too closely together to avoid making the page feel crowded.</p></li>
				</ul>
			</div>
		</div>
	</div>
	<div id="<?php echo $anchor3d ?>">
		<?php echo'<h3>' . $title3d . '</h3>'; // Gallery Page ?>
		<p>Galleries are used to showcase sections of a story that are primarily photo-driven.  Galleries can exist as their own page that includes supporting content, or a gallery can be placed in a modal overlay that is linked from other content.</p>		
		<div class="split">
			<div class="left"><a href="images/stories/galllerycomponents.png" data-lightbox="<?php echo $title3d ?>dos-1" class="img-link"><img src="images/stories/galllerycomponents.png" alt="<?php echo $title3d ?> Screen Shot" class="two-thirds"></a></div>
			<div class="right"><a href="images/stories/galllerymodal.png" data-lightbox="<?php echo $title3d ?>dos-1" class="img-link"><img src="images/stories/galllerymodal.png" alt="<?php echo $title3d ?> Screen Shot" class="two-thirds"></a></div>
		</div>
		<div class="split">
			<ul>
				<li>
					<h4><span class="letter">A</span>Gallery Headline</h4>
					<p>This is the primary heading of a gallery page, and is featured in any context where it is referenced, such as on a search results page. Headline placements and character counts can be found in the <a href="<?php echo $copy_guide_link?>182007678" target="_blank">copy specs visual guide</a>.</p>
				</li>
				<li>
					<h4><span class="letter">B</span>Gallery Metadata</h4>
					<p>Metadata is a short set of information that describes a gallery page's attributes.  Meta information includes a gallery's <em>author</em>, its <em>source url</em>, and the <em>date</em> it was published.</p>
				</li>
				<li>
					<h4><span class="letter">C</span>Introduction Content</h4>
					<p>This is the primary paragraph of a gallery page that introduces the content below. Character counts for introduction content can be found in the <a href="<?php echo $copy_guide_link?>182007678" target="_blank">copy specs visual guide</a>.</p>
				</li>
				<li class="break">
					<h4><span class="letter">D</span>Photo Gallery</h4>
					<p>Photo gallery carousels may hold any number of photos, but it is recommended that a maximum of 15 photographs be used in any given set.  Information on how to select photos can be found in the <?php echo $photo_guide_link //photography guide link ?>.</p>
				</li>
				<li>
					<h4><span class="letter optional">E</span>Photo Headline &amp; Description</h4>
					<p>While not required, photo headlines and descriptions help build context around a story. Character counts for photo headlines and descriptions can be found in the <a href="<?php echo $copy_guide_link?>182009564" target="_blank">copy specs visual guide.</a></p>
				</li>
				<li>
					<h4><span class="letter">F</span>Additional Page Content</h4>
					<p>This is the supporting content for the gallery page. Character counts for paragraph content can be found in the <a href="<?php echo $copy_guide_link?>182009564" target="_blank">copy specs visual guide.</a></p>
				</li>
			</ul>
		</div>
		<div class="split shaded">
			<h6><?php echo $title3d;?> Best Practices</h6>
			<div class="left do">
				<h5>Do</h5>
				<a href="images/stories/gallerydo.png" data-lightbox="<?php echo $title3d ?>dos-1" class="img-link"><img src="images/stories/gallerydo.png" alt="<?php echo $title3d ?> Do's Screen Shot" class=""></a>
				<ul>
					<li><p>Make sure that photos have headlines and captions.  Although photo headlines and captions are optional, associating text content with each photo helps an author effectively communicate their story. </p></li>
				</ul>
			</div>
			<div class="right dont break">
				<h5>Don't</h5>
				<a href="images/stories/gallerydont.png" data-lightbox="<?php echo $title3d ?>dos-1" class="img-link"><img src="images/stories/gallerydont-thumb.png" alt="<?php echo $title3d ?> Dont's Screen Shot" class=""></a>
				<ul>
					<li><p>Avoid using more than 15 photos in a carousel. Although a gallery can accomodate more than 15 photos, it is recommended to keep the quantity low to ensure that the reader will view all of them and continue through the story.</p></l>
				</ul>
			</div>
		</div>
	</div>
	<div id="<?php echo $anchor3e ?>">
		<?php echo'<h3>' . $title3e . '</h3>'; // Audio / Video Page ?>
		<p>Audio and video content pieces have the option to be treated as article pages that include supporting and related content. Audio and video content can also be placed within photo gallery modals.</p>
		<div class="split">
			<div class="left"><a href="images/stories/video.png" data-lightbox="<?php echo $title3e ?>dos-1" class="img-link"><img src="images/stories/video.png" alt="<?php echo $title3e ?> Screen Shot" class="two-thirds"></a></div>
			<div class="right"><a href="images/stories/audio.png" data-lightbox="<?php echo $title3e ?>1-dos-1" class="img-link"><img src="images/stories/audio.png" alt="<?php echo $title3e ?> Screen Shot" class="two-thirds"></a></div>
		</div>
		<div class="split">
			<ul>
				<li>
					<h4><span class="letter">A</span>Video Player</h4>
					<p>This is the primary video display area.</p>
				</li>
				<li>
					<h4><span class="letter">B</span>"Now Playing" Indicator Thumbnial</h4>
					<p>This indicator highlights the video that is currently playing. Short descriptions of each video appear beneath each thumbnail.</p>
				</li>
				<li>
					<h4><span class="letter">C</span>Title, Meta Information &amp; Content</h4>
					<p>This is where the title, meta information and text content of the video are located.</p>
				</li>
				<li class="break">
					<h4><span class="letter">D</span>Primary Audio Area</h4>
					<p>This is the area where an audio file is embedded.</p>
				</li>
				<li>
					<h4><span class="letter">E</span>"Now Playing" Indicator Thumbnail</h4>
					<p>This indicator highlights the audio clip that is currently playing. Short descriptions of each audio clip appear beneath each thumbnail.</p>
				</li>
				<li>
					<h4><span class="letter">F</span>Title, Meta Information &amp; Content</h4>
					<p>This is where the title, meta information and text content of the audio clip are located.</p>
				</li>
			</ul>
		</div>
		<div class="shaded">
			<h6><?php echo $title3e;?> Best Practices</h6>
			<div class="do">
				<ul>
					<li class="break"><p>Please review and follow the best practices for creating a <a href="#visualstorydosdonts">Visual Story Page</a>.</p></li>
				</ul>
			</div>
		</div>
	</div>
</section>